language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script:  "py.test -v --download tests/test_package.py"
notifications:
 webhooks:
  urls:
   - https://zapier.com/hooks/catch/n/d6fum/
  on_success: [always|never|change] # default: always
  on_failure: [always|never|change] # default: always